language: cpp
sudo: required
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq liblapack3gf liblapack-dev liblapack-picliblapack-pic liblapack-test
script: ./descargador.sh && make vecs && ./vecs
