language: cpp
before_install:
        - sudo apt-get install libblas-dev checkinstall
        - sudo apt-get install libblas-doc checkinstall
        - sudo apt-get install liblapacke-dev checkinstall
        - sudo apt-get install liblapack-doc checkinstall
        - ./descargador.sh
script: make vecs && ./vecs
sudo: required
