language: cpp
before_install:
        - sudo apt-get install -y libblas3gf
        - sudo apt-get install -y liblapack3gf
        - sudo apt-get install -y liblapack-dev
        - ./descargador.sh
script: make vecs && ./vecs
sudo: required
